
- id: jira-issue-in-commit-message
  name: jira-issue-in-commit-message
  description: Check presence of JIRA issue key in commit message.
  entry: python -m hooks.check_jira_commit
  language: python
  stages: [commit-msg]
